-- =====================================================
-- EMQF Monitoring Views
-- =====================================================

-- Latest score per dataset

CREATE OR REPLACE VIEW EMQF.QUALITY.EMQF_LATEST_QUALITY_SCORE AS
SELECT *
FROM EMQF.QUALITY.FACT_QUALITY_SCORE
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DATASET_CODE
    ORDER BY RUN_TIMESTAMP DESC
) = 1;


-- Domain Health

CREATE OR REPLACE VIEW EMQF.QUALITY.EMQF_DOMAIN_HEALTH AS
SELECT
    DOMAIN_ACRONYM,
    AVG(FINAL_QUALITY_SCORE) AS AVG_SCORE,
    COUNT(*) AS DATASET_COUNT
FROM EMQF.QUALITY.EMQF_QUALITY_SCORE_HISTORY
GROUP BY DOMAIN_ACRONYM;


-- Score Changes

CREATE OR REPLACE VIEW EMQF.QUALITY.EMQF_SCORE_CHANGES AS
WITH SCORES AS (
    SELECT
        DATASET_CODE,
        RUN_DATE,
        FINAL_QUALITY_SCORE,
        LAG(FINAL_QUALITY_SCORE)
            OVER (PARTITION BY DATASET_CODE ORDER BY RUN_DATE)
            AS PREVIOUS_SCORE
    FROM EMQF.QUALITY.EMQF_QUALITY_SCORE_HISTORY
)

SELECT
    DATASET_CODE,
    RUN_DATE,
    FINAL_QUALITY_SCORE,
    PREVIOUS_SCORE,
    FINAL_QUALITY_SCORE - PREVIOUS_SCORE AS SCORE_CHANGE
FROM SCORES
WHERE PREVIOUS_SCORE IS NOT NULL;


-- Alerts

CREATE OR REPLACE VIEW EMQF.QUALITY.EMQF_ALERTS AS
SELECT *
FROM EMQF.QUALITY.EMQF_SCORE_CHANGES
WHERE ABS(SCORE_CHANGE) >= 10;


-- SLA Status

CREATE OR REPLACE VIEW EMQF.QUALITY.EMQF_SLA_STATUS AS
SELECT
    DATASET_CODE,
    FINAL_QUALITY_SCORE,
    CASE
        WHEN FINAL_QUALITY_SCORE >= 95 THEN 'GREEN'
        WHEN FINAL_QUALITY_SCORE >= 85 THEN 'AMBER'
        ELSE 'RED'
    END AS SLA_STATUS
FROM EMQF.QUALITY.EMQF_LATEST_QUALITY_SCORE;
